import type { FromSchema } from 'json-schema-to-ts';
import * as schemas from './schemas';
export type CachedSearchMetadataParam = FromSchema<typeof schemas.CachedSearch.metadata>;
export type CachedSearchResponse200 = FromSchema<typeof schemas.CachedSearch.response['200']>;
export type CachedSearchResponse400 = FromSchema<typeof schemas.CachedSearch.response['400']>;
export type GetAvailabilityMetadataParam = FromSchema<typeof schemas.GetAvailability.metadata>;
export type GetAvailabilityResponse200 = FromSchema<typeof schemas.GetAvailability.response['200']>;
export type GetAvailabilityResponse400 = FromSchema<typeof schemas.GetAvailability.response['400']>;
export type GetRoutes1MetadataParam = FromSchema<typeof schemas.GetRoutes1.metadata>;
export type GetRoutes1Response200 = FromSchema<typeof schemas.GetRoutes1.response['200']>;
export type GetRoutes1Response400 = FromSchema<typeof schemas.GetRoutes1.response['400']>;
export type GetTripsMetadataParam = FromSchema<typeof schemas.GetTrips.metadata>;
export type GetTripsResponse200 = FromSchema<typeof schemas.GetTrips.response['200']>;
export type GetTripsResponse404 = FromSchema<typeof schemas.GetTrips.response['404']>;
export type LiveSearchBodyParam = FromSchema<typeof schemas.LiveSearch.body>;
export type LiveSearchResponse200 = FromSchema<typeof schemas.LiveSearch.response['200']>;
export type LiveSearchResponse400 = FromSchema<typeof schemas.LiveSearch.response['400']>;
export type LiveSearchResponse500 = FromSchema<typeof schemas.LiveSearch.response['500']>;
